site_name: {{ cookiecutter.project_name }} Documentation
copyright: Copyright &copy; {% now 'local', '%Y' %} {{ cookiecutter.full_name }}
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Security: security.md
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: deep-purple
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/
plugins:
  - search
  - autorefs
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import django"
            - "django.setup()"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
